### ISSUE TITLE
consider detecting / supporting docker compose (with space)

### ISSUE THREAD

**Issue by KissPeter** [isbang/compose-action#20]
Hint:
https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose
Thanks

**Comment by isbang** [comment]
Hi @KissPeter! Is there some reason why this feature is needed?

**Comment by nikicat** [comment]
For example [nektos/act](https://github.com/nektos/act) default images do not provide `docker-compose` binary

**Comment by martiGIT** [comment]
Also, the default installation of docker no longer requires additional installation of docker-compose (it is installed as docker module), which facilitates the work and maintenance of self-hosted runners
